allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - postcss@8.5.21
  - vercel@56.4.1
